# Use official lightweight Python image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Download nltk tokenizer during build
RUN python -m nltk.downloader punkt

# Copy project files
COPY . .

# Expose the port FastAPI will run on
EXPOSE 5000

# Run the API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
